server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://123.206.72.106:3306/management?characterEncoding=utf-8
    username: admin
    password: 123456
  jackson:
    default-property-inclusion: non_empty

mybatis:
  mapperLocations: classpath*:mapper/*.xml

logging:
  config: classpath:logback.xml

feign:
  httpclient:
    connection-timeout: 2000000
  hystrix:
    command:
      default:
        execution:
          isolation:
            strategy: SEMAPHORE
#    threadpool:
#      default:
#        coreSize: 10 #并发执行的最大线程数，默认10
#        maxQueueSize: 1000 #BlockingQueue的最大队列数，默认值-1
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 5000
        loggerLevel: none






