server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://123.206.72.106:3306/management
    username: admin
    password: 123456
  jackson:
    default-property-inclusion: non_empty

mybatis:
  mapperLocations: classpath*:mapper/*.xml


logging:
  level:
    root: INFO
    org.open.covid19: DEBUG


